# Generated by Django 4.0.5 on 2022-06-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeriesInstanceUID', models.IntegerField()),
                ('PatientID', models.IntegerField()),
                ('PatientName', models.CharField(max_length=200)),
                ('StudyInstanceUID', models.IntegerField()),
                ('InstancesInSeries', models.IntegerField()),
            ],
        ),
    ]
