# Generated by Django 4.0.5 on 2022-06-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='PatientID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='series',
            name='SeriesInstanceUID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='series',
            name='StudyInstanceUID',
            field=models.CharField(max_length=200),
        ),
    ]
